# coding: utf-8

"""
    PDF stamper

    The PDF Stamper API enables the possibility to add both static and dynamic stamps on existing PDFs. The stamps can consist of one or more barcode, hyperlink, image, line or text elements.    The flow is generally as follows:  1. Make a configuration containing the stamp information  2. Create a job specifying the desired configuration  3. Add one or more PDF files to the job  4. Start the job for processing  5. Retrieve the processed files    Full API Documentation: https://docs.sphereon.com/api/pdf-stamper/1.0  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com

    OpenAPI spec version: 1.0
    Contact: dev@sphereon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import models into sdk package
from .models.barcode_component import BarcodeComponent
from .models.blockchain_config import BlockchainConfig
from .models.blockchain_proof_component import BlockchainProofComponent
from .models.border import Border
from .models.canvas_component import CanvasComponent
from .models.color import Color
from .models.connector import Connector
from .models.content_request import ContentRequest
from .models.content_response import ContentResponse
from .models.default_job_settings import DefaultJobSettings
from .models.dimension import Dimension
from .models.error import Error
from .models.error_response import ErrorResponse
from .models.hyperlink_component import HyperlinkComponent
from .models.image_component import ImageComponent
from .models.input_result_location import InputResultLocation
from .models.input_settings import InputSettings
from .models.lifecycle import Lifecycle
from .models.line_component import LineComponent
from .models.pdf_stamper_job_request import PdfStamperJobRequest
from .models.pdf_stamper_job_result import PdfStamperJobResult
from .models.point import Point
from .models.rgb_value import RGBValue
from .models.result_settings import ResultSettings
from .models.stamp_component import StampComponent
from .models.stamper_config import StamperConfig
from .models.stamper_config_response import StamperConfigResponse
from .models.storage_location import StorageLocation
from .models.stream_location import StreamLocation
from .models.text_component import TextComponent

# import apis into sdk package
from .apis.config_api import ConfigApi
from .apis.jobs_api import JobsApi
from .apis.synchronous_api import SynchronousApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
