# coding: utf-8

"""
    PDF stamper

    The PDF Stamper API enables the possibility to add both static and dynamic stamps on existing PDFs. The stamps can consist of one or more barcode, hyperlink, image, line or text elements.    The flow is generally as follows:  1. Make a configuration containing the stamp information  2. Create a job specifying the desired configuration  3. Add one or more PDF files to the job  4. Start the job for processing  5. Retrieve the processed files    Full API Documentation: https://docs.sphereon.com/api/pdf-stamper/1.0  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com

    OpenAPI spec version: 1.0
    Contact: dev@sphereon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class Connector(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, components=None, offset=None, horizontal_anchor_point=None, vertical_anchor_point=None):
        """
        Connector - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'components': 'list[StampComponent]',
            'offset': 'Point',
            'horizontal_anchor_point': 'str',
            'vertical_anchor_point': 'str'
        }

        self.attribute_map = {
            'components': 'components',
            'offset': 'offset',
            'horizontal_anchor_point': 'horizontalAnchorPoint',
            'vertical_anchor_point': 'verticalAnchorPoint'
        }

        self._components = components
        self._offset = offset
        self._horizontal_anchor_point = horizontal_anchor_point
        self._vertical_anchor_point = vertical_anchor_point

    @property
    def components(self):
        """
        Gets the components of this Connector.


        :return: The components of this Connector.
        :rtype: list[StampComponent]
        """
        return self._components

    @components.setter
    def components(self, components):
        """
        Sets the components of this Connector.


        :param components: The components of this Connector.
        :type: list[StampComponent]
        """

        self._components = components

    @property
    def offset(self):
        """
        Gets the offset of this Connector.
        The optional offset of the components relative to the parent component

        :return: The offset of this Connector.
        :rtype: Point
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """
        Sets the offset of this Connector.
        The optional offset of the components relative to the parent component

        :param offset: The offset of this Connector.
        :type: Point
        """

        self._offset = offset

    @property
    def horizontal_anchor_point(self):
        """
        Gets the horizontal_anchor_point of this Connector.
        The horizontal anchor point to which the components are connected

        :return: The horizontal_anchor_point of this Connector.
        :rtype: str
        """
        return self._horizontal_anchor_point

    @horizontal_anchor_point.setter
    def horizontal_anchor_point(self, horizontal_anchor_point):
        """
        Sets the horizontal_anchor_point of this Connector.
        The horizontal anchor point to which the components are connected

        :param horizontal_anchor_point: The horizontal_anchor_point of this Connector.
        :type: str
        """
        allowed_values = ["LEFT", "CENTER", "RIGHT"]
        if horizontal_anchor_point not in allowed_values:
            raise ValueError(
                "Invalid value for `horizontal_anchor_point` ({0}), must be one of {1}"
                .format(horizontal_anchor_point, allowed_values)
            )

        self._horizontal_anchor_point = horizontal_anchor_point

    @property
    def vertical_anchor_point(self):
        """
        Gets the vertical_anchor_point of this Connector.
        The vertical anchor point to which the components are connected

        :return: The vertical_anchor_point of this Connector.
        :rtype: str
        """
        return self._vertical_anchor_point

    @vertical_anchor_point.setter
    def vertical_anchor_point(self, vertical_anchor_point):
        """
        Sets the vertical_anchor_point of this Connector.
        The vertical anchor point to which the components are connected

        :param vertical_anchor_point: The vertical_anchor_point of this Connector.
        :type: str
        """
        allowed_values = ["TOP", "MIDDLE", "BOTTOM"]
        if vertical_anchor_point not in allowed_values:
            raise ValueError(
                "Invalid value for `vertical_anchor_point` ({0}), must be one of {1}"
                .format(vertical_anchor_point, allowed_values)
            )

        self._vertical_anchor_point = vertical_anchor_point

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
