# coding: utf-8

"""
    PDF stamper

    The PDF Stamper API enables the possibility to add both static and dynamic stamps on existing PDFs. The stamps can consist of one or more barcode, hyperlink, image, line or text elements.    The flow is generally as follows:  1. Make a configuration containing the stamp information  2. Create a job specifying the desired configuration  3. Add one or more PDF files to the job  4. Start the job for processing  5. Retrieve the processed files    Full API Documentation: https://docs.sphereon.com/api/pdf-stamper/1.0  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com

    OpenAPI spec version: 1.0
    Contact: dev@sphereon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class LineComponent(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, border=None, connectors=None, offset=None, color=None, line_to=None, line_width=None):
        """
        LineComponent - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'border': 'Border',
            'connectors': 'list[Connector]',
            'offset': 'Point',
            'color': 'Color',
            'line_to': 'Point',
            'line_width': 'float'
        }

        self.attribute_map = {
            'border': 'border',
            'connectors': 'connectors',
            'offset': 'offset',
            'color': 'color',
            'line_to': 'lineTo',
            'line_width': 'lineWidth'
        }

        self._border = border
        self._connectors = connectors
        self._offset = offset
        self._color = color
        self._line_to = line_to
        self._line_width = line_width

    @property
    def border(self):
        """
        Gets the border of this LineComponent.
        The border of the component

        :return: The border of this LineComponent.
        :rtype: Border
        """
        return self._border

    @border.setter
    def border(self, border):
        """
        Sets the border of this LineComponent.
        The border of the component

        :param border: The border of this LineComponent.
        :type: Border
        """

        self._border = border

    @property
    def connectors(self):
        """
        Gets the connectors of this LineComponent.
        Connectors containing components that can be positioned relative to this component

        :return: The connectors of this LineComponent.
        :rtype: list[Connector]
        """
        return self._connectors

    @connectors.setter
    def connectors(self, connectors):
        """
        Sets the connectors of this LineComponent.
        Connectors containing components that can be positioned relative to this component

        :param connectors: The connectors of this LineComponent.
        :type: list[Connector]
        """

        self._connectors = connectors

    @property
    def offset(self):
        """
        Gets the offset of this LineComponent.
        The offset of the component relative to the parent component

        :return: The offset of this LineComponent.
        :rtype: Point
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """
        Sets the offset of this LineComponent.
        The offset of the component relative to the parent component

        :param offset: The offset of this LineComponent.
        :type: Point
        """

        self._offset = offset

    @property
    def color(self):
        """
        Gets the color of this LineComponent.
        The color of the line

        :return: The color of this LineComponent.
        :rtype: Color
        """
        return self._color

    @color.setter
    def color(self, color):
        """
        Sets the color of this LineComponent.
        The color of the line

        :param color: The color of this LineComponent.
        :type: Color
        """

        self._color = color

    @property
    def line_to(self):
        """
        Gets the line_to of this LineComponent.
        The point to which the line should be drawn. The origin is derived of the X and Y coordinate of the component itself (bottom-left) 

        :return: The line_to of this LineComponent.
        :rtype: Point
        """
        return self._line_to

    @line_to.setter
    def line_to(self, line_to):
        """
        Sets the line_to of this LineComponent.
        The point to which the line should be drawn. The origin is derived of the X and Y coordinate of the component itself (bottom-left) 

        :param line_to: The line_to of this LineComponent.
        :type: Point
        """

        self._line_to = line_to

    @property
    def line_width(self):
        """
        Gets the line_width of this LineComponent.
        The thickness of the line

        :return: The line_width of this LineComponent.
        :rtype: float
        """
        return self._line_width

    @line_width.setter
    def line_width(self, line_width):
        """
        Sets the line_width of this LineComponent.
        The thickness of the line

        :param line_width: The line_width of this LineComponent.
        :type: float
        """

        self._line_width = line_width

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
