# coding: utf-8

"""
    PDF stamper

    The PDF Stamper API enables the possibility to add both static and dynamic stamps on existing PDFs. The stamps can consist of one or more barcode, hyperlink, image, line or text elements.    The flow is generally as follows:  1. Make a configuration containing the stamp information  2. Create a job specifying the desired configuration  3. Add one or more PDF files to the job  4. Start the job for processing  5. Retrieve the processed files    Full API Documentation: https://docs.sphereon.com/api/pdf-stamper/1.0  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com

    OpenAPI spec version: 1.0
    Contact: dev@sphereon.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class TextComponent(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, border=None, connectors=None, offset=None, non_stroking_color=None, font_name=None, font_size=None, text=None, line_spacing=None):
        """
        TextComponent - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'border': 'Border',
            'connectors': 'list[Connector]',
            'offset': 'Point',
            'non_stroking_color': 'Color',
            'font_name': 'str',
            'font_size': 'float',
            'text': 'str',
            'line_spacing': 'float'
        }

        self.attribute_map = {
            'border': 'border',
            'connectors': 'connectors',
            'offset': 'offset',
            'non_stroking_color': 'nonStrokingColor',
            'font_name': 'fontName',
            'font_size': 'fontSize',
            'text': 'text',
            'line_spacing': 'lineSpacing'
        }

        self._border = border
        self._connectors = connectors
        self._offset = offset
        self._non_stroking_color = non_stroking_color
        self._font_name = font_name
        self._font_size = font_size
        self._text = text
        self._line_spacing = line_spacing

    @property
    def border(self):
        """
        Gets the border of this TextComponent.
        The border of the component

        :return: The border of this TextComponent.
        :rtype: Border
        """
        return self._border

    @border.setter
    def border(self, border):
        """
        Sets the border of this TextComponent.
        The border of the component

        :param border: The border of this TextComponent.
        :type: Border
        """

        self._border = border

    @property
    def connectors(self):
        """
        Gets the connectors of this TextComponent.
        Connectors containing components that can be positioned relative to this component

        :return: The connectors of this TextComponent.
        :rtype: list[Connector]
        """
        return self._connectors

    @connectors.setter
    def connectors(self, connectors):
        """
        Sets the connectors of this TextComponent.
        Connectors containing components that can be positioned relative to this component

        :param connectors: The connectors of this TextComponent.
        :type: list[Connector]
        """

        self._connectors = connectors

    @property
    def offset(self):
        """
        Gets the offset of this TextComponent.
        The offset of the component relative to the parent component

        :return: The offset of this TextComponent.
        :rtype: Point
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """
        Sets the offset of this TextComponent.
        The offset of the component relative to the parent component

        :param offset: The offset of this TextComponent.
        :type: Point
        """

        self._offset = offset

    @property
    def non_stroking_color(self):
        """
        Gets the non_stroking_color of this TextComponent.
        The color of the text

        :return: The non_stroking_color of this TextComponent.
        :rtype: Color
        """
        return self._non_stroking_color

    @non_stroking_color.setter
    def non_stroking_color(self, non_stroking_color):
        """
        Sets the non_stroking_color of this TextComponent.
        The color of the text

        :param non_stroking_color: The non_stroking_color of this TextComponent.
        :type: Color
        """

        self._non_stroking_color = non_stroking_color

    @property
    def font_name(self):
        """
        Gets the font_name of this TextComponent.
        The font of the text

        :return: The font_name of this TextComponent.
        :rtype: str
        """
        return self._font_name

    @font_name.setter
    def font_name(self, font_name):
        """
        Sets the font_name of this TextComponent.
        The font of the text

        :param font_name: The font_name of this TextComponent.
        :type: str
        """

        self._font_name = font_name

    @property
    def font_size(self):
        """
        Gets the font_size of this TextComponent.
        The size of the text

        :return: The font_size of this TextComponent.
        :rtype: float
        """
        return self._font_size

    @font_size.setter
    def font_size(self, font_size):
        """
        Sets the font_size of this TextComponent.
        The size of the text

        :param font_size: The font_size of this TextComponent.
        :type: float
        """

        self._font_size = font_size

    @property
    def text(self):
        """
        Gets the text of this TextComponent.
        The text that will be displayed

        :return: The text of this TextComponent.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """
        Sets the text of this TextComponent.
        The text that will be displayed

        :param text: The text of this TextComponent.
        :type: str
        """

        self._text = text

    @property
    def line_spacing(self):
        """
        Gets the line_spacing of this TextComponent.
        Linespacing ratio. The default is 0.5 (meaning half a line height). The spacing is only applicable to newlines within a single text component

        :return: The line_spacing of this TextComponent.
        :rtype: float
        """
        return self._line_spacing

    @line_spacing.setter
    def line_spacing(self, line_spacing):
        """
        Sets the line_spacing of this TextComponent.
        Linespacing ratio. The default is 0.5 (meaning half a line height). The spacing is only applicable to newlines within a single text component

        :param line_spacing: The line_spacing of this TextComponent.
        :type: float
        """

        self._line_spacing = line_spacing

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
